### ISSUE TITLE
Tiered gear from wrong class does not get filtered out.

### ISSUE THREAD

**Issue by KurtzPT** [BoxximusPrime/WhoGotLoots#5]
As title says, if a piece of tier gear from another class drops, it won't be filtered out. I was doing timewalking and a rogue tier piece dropped while I was druid and it showed in the main window.

**Comment by BoxximusPrime** [comment]
Did you have "hide unequippable" enabled?

**Comment by KurtzPT** [comment]
> Did you have "hide unequippable" enabled?

I did, it was actually the only piece of gear that happened to not being filtered out. I'm assuming its because of being a tier piece.

**Comment by KurtzPT** [comment]
Captured the issue, playing with mage:

![image](https://github.com/user-attachments/assets/7bcfe758-2e61-46d0-8cb6-7d8fcf2dfe36)

**Comment by BoxximusPrime** [comment]
Should be fixed now, lemme know if it has any issues.
